version: "3"

vars:
  DB_URL: "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable"

tasks:
  setup:
    desc: Setup the project
    cmds:
      - go mod tidy
      - go mod tidy -modfile=go.tool.mod

  upgrade:
    desc: Upgrade dependencies or tools (use `task upgrade -- tool`)
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" = "tool" ]; then
          go get -modfile=go.tool.mod tool
        else
          go tool -modfile=go.tool.mod go-mod-upgrade
        fi

  network:
    cmds:
      - docker network inspect bank-network || docker network create bank-network

  postgres:
    cmds:
      - docker run --name postgres12 --network bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:12-alpine

  createdb:
    cmds:
      - docker exec -it postgres12 createdb --username=root --owner=root simple_bank

  dropdb:
    cmds:
      - docker exec -it postgres12 dropdb simple_bank

  migrateup:
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path db/migration/ -database "{{.DB_URL}}" --verbose up

  migrateup1:
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path db/migration/ -database "{{.DB_URL}}" --verbose up 1

  migratedown:
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path db/migration/ -database "{{.DB_URL}}" --verbose down

  migratedown1:
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path db/migration/ -database "{{.DB_URL}}" --verbose down 1

  new_migration:*:
    vars:
      NAME: "{{index .MATCH 0}}"
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latestcreate -ext sql -dir db/migration -seq {{.NAME}}

  db_docs:
    cmds:
      - dbdocs build doc/db.dbml --project simple-bank

  db_schema:
    cmds:
      - dbml2sql --postgres -o doc/schema.sql doc/db.dbml

  sqlc:
    cmds:
      - go tool -modfile=go.tool.mod sqlc generate

  test:
    cmds:
      - go test -v -cover -short ./...

  server:
    cmds:
      - go run main.go

  proto:
    cmds:
      - rm -f gen/pb/*.go
      - rm -rf doc/swagger/pb
      - protoc --proto_path=proto --go_out=gen --go_opt=paths=source_relative
        --go-grpc_out=gen --go-grpc_opt=paths=source_relative
        --grpc-gateway_out=gen --grpc-gateway_opt=paths=source_relative
        --openapiv2_out=doc/swagger --openapiv2_opt=allow_merge=true,merge_file_name=simple_bank
        proto/pb/v1/*.proto

  evans:
    cmds:
      - evans --host localhost --port 9090 -r repl

  mock:
    cmds:
      - go tool -modfile=go.tool.mod mockgen -package mockdb -destination db/mock/store.go github.com/yelaco/simple-bank/db/sqlc Store

  doc-api:
    desc: View api documentation in Swagger UI
    ignore_error: true
    vars:
      detach:
        sh: echo $DETACH
      pwd:
        sh: pwd
    cmds:
      - |
        set +e
        docker inspect simple-bank-doc > /dev/null 2>&1
        if [ $? -eq 0 ]; then
          docker start {{if not .detach}}-a{{end}} simple-bank-doc
        else
          docker run {{if .detach}}-d{{end}} -p 7101:8080 -e SWAGGER_JSON=/doc/swagger/simple_bank.swagger.json -v {{.pwd}}/doc/swagger:/doc/swagger --name simple-bank-doc swaggerapi/swagger-ui
        fi

  redis:
    cmds:
      - docker run --name redis -p 6379:6379 -d redis/redis-stack:7.2.0-v17
